### PR TITLE
Add a separate parameter to shorten the address of a gas station

### PR DESCRIPTION
**Pull request by Sindbad6**

### CODE REVIEW

**Comment by fewieden** [comment]
I changed the base branch from master to develop.

Can you please add the config option to the readme file as well?

There are some issues on travis and codeclimate with your contribution.
Can you fix them?

**Comment by Sindbad6** [comment]
Am 25.03.2017 um 12:49 schrieb fewieden:
>
> I changed the base branch from master to develop.
>
> Can you please add the config option to the readme file as well?
>
I changed the readme file. But I commit it to the "master", what's
probably wrong again. I have to say, that the handling of Github, is
much more difficult for me, as I was thinking of.
>
> There are some issues on travis and codeclimate with your contribution.
> Can you fix them?
>
I dont't know. I will have a look on it. I will try my very best. But
this have to wait a little bit not.

**Comment by fewieden** [comment]
there is only this issue on travis

```
/home/travis/build/fewieden/MMM-Fuel/MMM-Fuel.js

  252:1  error  Trailing spaces not allowed  no-trailing-spaces
```

and code climate complains about duplicate code

https://codeclimate.com/github/fewieden/MMM-Fuel/pull/18

If you want I can take care about it this weekend.

**Comment by fewieden** [comment]
Close due to inactivity

**Pull request closed without merging**
