### PR TITLE
Added properties decimalSeparator and superscriptNine and added the ability to specify additional fuel station ids

### PR DESCRIPTION
**Pull request by TheDuffman85**
Property **decimalSeparator** sets the decimal separator for numbers.
Property **superscriptNine** displays the last nine after decimal seperator as superscript nine.

grafik

### CODE REVIEW

**Comment by TheDuffman85** [comment]
I added also the ability to specify additional fuel station ids. This relates to feature request #53.

**Comment by fewieden** [comment]
@TheDuffman85 thank you for your contribution, I will have a look in the next few days if I can find some optimizations to your changes.

**Comment by fewieden** [comment]
@TheDuffman85 I changed your two new config options:
- supescriptNine: If a user shows 3 fraction digits it always puts them as superscript text now, not just a nine.
- decimalSeparator: It's formatting the number format now based on the user's locale.

I will try to have a look into your change regarding data by station IDs

**Comment by TheDuffman85** [comment]
Hi @fewieden,

sounds good. I didn't even know that there is a fuction for superscript in JS. I'm a full stack .NET developer, my JS knowledge is limited.

**Comment by fewieden** [comment]
@TheDuffman85 I renamed the config option to `stationIds`. I also made a change in how it works. Instead of letting both modes (byRadius and byId) work in parallel, it is just one at a time now. Due to this, I was able to reduce the API requests by a lot. We had issues before where some API keys were blocked because of too many requests.

I need to test my changes a bit more before I will create a new release.

**Comment by TheDuffman85** [comment]
@fewieden Okay. Let's at least give the possibility to use both modes at the same time. The radius search is only one API call. It's very convenient to query a small radius around your home and add a few selected stations around your commute. I'm using it this way since a week and haven't beeing blocked.

**Comment by TheDuffman85** [comment]
Another way to optimize the API requests would be to make the details call only the first time and cache the distance. After that we could use the prices call. It's unlikely that the fuel stations will move :)

**Comment by TheDuffman85** [comment]
@fewieden What do you think? I could implement the caching mechanism.

**Comment by fewieden** [comment]
@TheDuffman85 the details request is already cached and performed once after the start of the mirror.

I was thinking about merging the two modes the last few days:

|+|-|
|---|---|
|Faster to configure|Doesn't give you the correct prices, because the two endpoints work differently|
|Allows usage of more than 10 stations (everything in radius + 10)|If you have a big radius but want to make sure one is always considered you end up with a possible duplicate using up space|

The configuration is a one-time investment and is not hard to do with the map finder. Most people always go to the same handful of stations so being able to use more is probably not a big benefit. On the other hand, the pricing values work differently between the two endpoints. The radius gives only values for the few cheapest. We currently display `> HIGHEST_RETURNED_PRICE` for the rest, but the other endpoint returns a price for all stations if they are open. What should come first >1.37€ or 1.39€? We don't know because the first one could be cheaper but also way more expensive than the second.

For me, the disadvantages overweigh the advantages, also because the main target of the module is to allow you to save money which is not given with the price problem explained above.

**Comment by fewieden** [comment]
@TheDuffman85 I had another look into the returned data. The point I made about the different pricing above is not valid. This was for another provider integrated into this module.

Therefore I see the following points necessary to make this work nicely:
- [ ] Filter out duplicates from radius and id search (they both have an UUID that we need to check for a match).
- [ ] Possibility to disable radius search. Either by adding another config option or by setting radius to `0` or `false`.
- [ ] Add documentation about increased requests and suggestion to increase the `updateInterval`

**Comment by TheDuffman85** [comment]
@fewieden Thank you for reconsidering. I've implemented the open points. 

- [x]  Filter out duplicates from radius and id search (they both have an UUID that we need to check for a match).
- [x] Possibility to disable radius search. Either by adding another config option or by setting radius to 0 or false.
- [x] Add documentation about increased requests and suggestion to increase the updateInterval

**Comment by TheDuffman85** [comment]
@ Why did you change the unit from km to kilometer? It will take much more space now.

**Comment by fewieden** [comment]
@TheDuffman85 I switched from the raw display of the unit to `Intl.NumberFormat`. This allows us to have easier localization with the right decimal symbol. It still only shows two characters for the unit as before.

image

**Comment by TheDuffman85** [comment]
My bad. I forgot to update the template. For testing I only replaced the API with my latest changes. This was why it showed kilometer for me.

**Comment by TheDuffman85** [comment]
@fewieden are there still open points that prevent you to merge the changes?

**Comment by fewieden** [comment]
@TheDuffman85 there are no more open points, I just had not much time during the last month

**Comment by fewieden** [comment]
@TheDuffman85 I just released version 2.2.0 containing your changes, thank you again.

**Pull request merged**
